[package]
name = "video-to-gif-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg = "0.3.0"
clap = "2.19.3"